version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spring-batch-demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres